---
title: "Untitled"
author: "Lærke Brædder"
date: "3/2/2021"
output: html_document
---
```{r}
pacman::p_load(tidyverse,
               here,
               network,
               igraph,
               ggraph,
               tidygraph,
               patchwork)
```


```{r}
# Loading data
EdgesDataset_s0friends <- read_csv(
  "class5_Archive/CogSci19S0_NetworkFriends.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s0friends <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s1friends <- read_csv(
  "class5_Archive/CogSci19S1_NetworkFriends.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1friends <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s1fun <- read_csv(
  "class5_Archive/CogSci19S1_NetworkFun.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1fun <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s1studious <- read_csv(
  "class5_Archive/CogSci19S1_NetworkStudious.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1studious <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s1sg <- read_csv(
  "class5_Archive/CogSci19S1_NetworkStudyGroup.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1sg <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s4friends <- read_csv(
  "class5_Archive/CogSci19S4_NetworkFriends.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1sg <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s4fun <- read_csv(
  "class5_Archive/CogSci19S4_NetworkFun.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1sg <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)


# Loading data
EdgesDataset_s4studious <- read_csv(
  "class5_Archive/CogSci19S4_NetworkStudious.csv") %>% 
  subset(
    !is.na(to) & !is.na(from) & !is.na(weight) # removing odd NAs
  )
# Removing trolls
EdgesDataset_s1sg <- EdgesDataset %>% subset(
  !(to %in% c("fake0", "fake", "100", "1")) & !(from %in% c("fake0", "fake", "100", "1") & !is.na(to) & !is.na(from))
)
```


```{r}
#Creating list of nodes - creating a list of unique IDs on one of the 4th sem data sets
EdgesDataset_s4friends_nodes <- data.frame(ID=unique(c(
  EdgesDataset_s4friends$from,
  EdgesDataset_s4friends$from,
  EdgesDataset_s4friends$from,
  EdgesDataset_s4friends$to,
  EdgesDataset_s4friends$to,
  EdgesDataset_s4friends$to)))

Graph <-
  graph_from_data_frame(d = EdgesDataset_s4friends,
                        vertices = EdgesDataset_s4friends_nodes,
                        directed = TRUE)

E(Graph)$arrow.mode <- 0
V(Graph)$label <- ""
E(Graph)$width <- edge_attr(Graph)$weight

plot(Graph,
     layout = layout_on_sphere, # Explore layouts!
     edge.arrow.size = 0.2)

wc1 <- cluster_walktrap(Graph)
plot(wc1, Graph)


```

